print("Python is an interpreted, high-level general-purpose programming language developed by Guido van Rossum and first released in 1991")
print('#' * 99)
print("Python's design philosophy emphasizes code readability with its notable use of significant whitespaces")
print("The language's core philosophy is summarized in the document 'The Zen of Python'")
print('#' * 99)
print("The Zen of Python is a collection of '19 guiding principles' for writing computer programs that influence the design of the Python programming language")
print("It is included as an easter egg in the Python interpreter which can be displayed by entering\nimport this\n")
import this

print('#' * 99)
print("Python is a powerful general-purpose programming language with applications ranging form web and internet development, scientific and numeric (mathematics, science, and engineering, data analysis and modelling, deep learning, machine learning, AI, visualization etc), creating Desktop GUIs, Software and game development, Education, scripting, Network Programming among others ")
print('#' * 99)
print("A few points to note before learning Python:")
print("Python is case-sensitive so 'name' and 'Name' are not the same")
print("Spacing matters in Python - Python is not heavy on syntax so it relies heavily on spacing to delimit code blocks")
print("You will inevitably run into errors as you learn Python. Errors do not make you a bad programmer, it is just a way for the computer to tell you that it does not quite understand what you have instructed it to do. Use errors as a learning tool, don't let them be a deterrent or discouragement in your learning to code journey")